### ISSUE TITLE
[Feature]: User-Installable apps support

### ISSUE THREAD

**Issue by Wondermarin** [discordx-ts/discordx#1061]
### Feature?

Hi there!

As of March 18th, [user-installable apps are now available](https://discord.com/developers/docs/change-log#userinstallable-apps-preview). I tried to find out if this library supports the new feature, but couldn't find anything relevant in the documentation or examples. Is this currently implemented? If not, are there any plans to add it?

Thanks!

### Package

discordx

**Comment by samarmeena** [comment]
@Wondermarin sure, https://github.com/discordjs/discord.js/pull/10348 is in progress and yet to be merged by discordjs. Once they release it, will provide support instantly.

Thank you for letting me know about upcoming change to discordjs.

**Comment by samarmeena** [comment]
yes, I was aware. But they have not released it in stable release. And currently, we are not supporting development branch.

**Comment by Chriscodinglife** [comment]
Was scratching my head over how I could get my app slash commands to work within private and group DMs upon user install. Hopefully, this workaround is good for now...

I follow the same steps of creating an invite link for a server but also check off for the user.

SlashCommandBuilder() from discord.js returns a JSON, so you can add the `integration_types` and `contexts` properties to it manually and then pass it into a data object for registration. 

```
const command = new SlashCommandBuilder()
                        .setName("test")
                        .setDescription("send test 123")
    
command["integration_types"] = [0, 1];
command["contexts"] = [0, 1, 2];

{ data: command, async execute(interaction) await interaction.reply("Test 123") }
```

My private DM with another user
![image](https://github.com/user-attachments/assets/8c867068-b2fb-4b1c-a52e-74c0377a397b)
![image](https://github.com/user-attachments/assets/2160fa93-a0a8-4cb5-b44f-78745abd2b77)

looking forward to official support though 👍

**Comment by samarmeena** [comment]
Let me know, once you guys test it.
