### ISSUE TITLE
[Feature]: Request for more verbosity levels

### ISSUE THREAD

**Issue by parnavh** [discordx-ts/discordx#1076]
### Feature?

Currently when the bot starts you get a detailed list of all the commands, modals etc along with their status in various servers. While this is helpful in an development environment, it clutters up the production logs. I think we should consider allowing users to tone down the verbosity of these message to their liking.

Proposed changes:
- Allow initial logs to be disabled completely
- Allow guild only logs to be disabled (which lists all guilds and shows the status of every command)
- Option to display all logs for a category in a single line
```
client >> application commands
        >> settings (Settings.Settings)
                >> voice: subcommandgroup (VoiceSettings.VoiceSettings)
                                >> enable: subcommand (VoiceSettings.enable)
                                >> disable: subcommand (VoiceSettings.disable)
```
```
client - application.commands - settings.voice.enable settings.voice.disable
```
This allows for important information to be present in the logs while not cluttering the logs 
- Allow custom callback function to handle the initial logging
Allow a custom function to be passed to `bot.initApplicationCommands()` as an option which will then log out in whatever format the user wants. This will most likely not be used a lot so maybe not worth implementing if it is complicated

### Package

discordx

**Comment by parnavh** [comment]
I am ready to help out in any way I can, let me know if this is something that the maintainers think will be a good addition to the project

**Comment by vijayymmeena** [comment]
In production, use silent feature.

**Comment by vijayymmeena** [comment]
Per guild logs, should be not there. Why aren't you using global command instead?

**Comment by parnavh** [comment]
> Per guild logs, should be not there. Why aren't you using global command instead?
Oh yes, my bad about the guild logs, I mistook the dev logs for the production logs

> In production, use silent feature.
I didn't realize this existed, my bad again. Is it present in the docs?

**Comment by vijayymmeena** [comment]
It's only visible in api docs.

https://discordx.js.org/api/discordx/interfaces/ClientOptions.html#silent

**Comment by vijayymmeena** [comment]
@parnavh is there anything else, I can help with?

**Comment by parnavh** [comment]
I think there should be some kind of mention in the docs, let me know if you'd like for me to add it to the docs. But apart from that all good! I didn't realise that the library already supported this.

Thank you!

**Comment by vijayymmeena** [comment]
@parnavh in this page, you can make pr to add new section that describe all client options.

https://discordx.js.org/docs/discordx/basics/client
