### ISSUE TITLE
[Bug]: Infered Slash command names from functions needs validation

### ISSUE THREAD

**Issue by VictoriqueMoe** [discordx-ts/discordx#857]
### What happened?

When you use `@Slash` without a `name` prop, the name of the command is taken from the method name.

This is fine, but `@Slash` validation (caseing, etc..) is done purely by TS typing and not actual code. this means if you have the following simple code:

```ts
@Discord()
class Example {
  @Slash()
  myMethod(
    @SlashOption({ name: "message" }) message: string,
    interaction: CommandInteraction
  ): void {
    interaction.reply(`:wave: from ${interaction.user}: ${message}`);
  }
}
```

Then you will get a very cryptic error from the Discord API (and we all know how fun Discord API errors are)..

this can be hard to figure out what command is wrong when you manage a bot of many commands. 

Validation of the command name needs to be done in code, as inferred name from the function bypasses Typescript type validation.  

### Reproduction

```ts
@Discord()
class Example {
  @Slash()
  myMethod(
    @SlashOption({ name: "message" }) message: string,
    interaction: CommandInteraction
  ): void {
    interaction.reply(`:wave: from ${interaction.user}: ${message}`);
  }
}
```

### Package

discordx

### Version

Stable

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
I am aware about this, inference should be done at developers own risk.

**Comment by oceanroleplay** [comment]
I think would be good to put this as warning in docs

**Comment by drph4nt0m** [comment]
I think since we are making it default to use the function name as command name (the specific name is there but its not default), we should handle it somehow from the package level also.

**Comment by oceanroleplay** [comment]
we can't replicate discord validation

**Comment by oceanroleplay** [comment]
at least not perfectly

**Comment by VictoriqueMoe** [comment]
> we can't replicate discord validation

we can replicate the SAME validation as done in the typing, this is important for consistency and urge it to be done

**Comment by oceanroleplay** [comment]
I am not sure, how to make one, so I can't help it.

**Comment by VictoriqueMoe** [comment]
> 

I think having just enforcing the case is enough for now

**Comment by oceanroleplay** [comment]
> I think would be good to put this as warning in docs

this will resolve the issue, there are x reasons for this type of problems, if we deal with some validation, we will just end up creating more x problems. so a simple warning for those, who are not familiar would be good.

**Comment by VictoriqueMoe** [comment]
> this will resolve the issue, there are x reasons for this type of problems, if we deal with some validation, we will just end up creating more x problems. so a simple warning for those, who are not familiar would be good.

Didn't you create the validation in the typing? just use that but as code.

**Comment by oceanroleplay** [comment]
type validation something, help while code. discord is returning error same as we return error, in runtime. I see no useful point of doing validation in dx.

> just use that but as code
idk, type are not codes.

**Comment by VictoriqueMoe** [comment]
> type validation something, help while code. discord is returning error same as we return error, in runtime. I see no useful point of doing validation in dx.
> 
> > just use that but as code
> 
> idk, type are not codes.

take the same logic you used to create the types and put it into code. if your argument is "we can't replicate discord validation" then why did you go through so much effort to make a massive complex TS type to validate it?
