### ISSUE TITLE
[Feature]: add the commandID to "DApplicationCommand"

### ISSUE THREAD

**Issue by B0tis** [discordx-ts/discordx#865]
### Feature?

Hi, I would like to mention Slash commands in my bot message and that via "MetadataStorage" but I noticed that the commandID is not there yet.

I would be very kind if you could add this feature.

### Package

discordx

**Comment by oceanroleplay** [comment]
command id is not something our library create, it is snowflake id generated by discord. You can fetch discord commands to retrieve application command id.

**Comment by B0tis** [comment]
lol, thx
