### ISSUE TITLE
[Feature]: Add Rate Limit to buttons

### ISSUE THREAD

**Issue by B0tis** [discordx-ts/discordx#866]
### Feature?

Hi, currently it is possible to Rate Limit the usage of commands but not from Button Interactions.

It would be nice that this Feature would be added if possible :)

### Package

@discordx/utilities

**Comment by TeamWolfyta** [comment]
Are you wanting to know if there is a way to rate limit buttons or commands ?

**Comment by B0tis** [comment]
For Buttons, it would be nice to know, for Commands it's already possible

**Comment by TeamWolfyta** [comment]
I know something for commands already exists, It's just the way you phrased your message was a bit all over the place.

Why would you need a rate limit for buttons ? In some way discord makes you wait a bit before each button press anyways.

**Comment by B0tis** [comment]
Well, I would like to have the possibility that the User can only use the Button once every Minute...

**Comment by TeamWolfyta** [comment]
Have you tried using `@RateLimit` on a button since if I remember correctly button has a interaction parameter which is what `RateLimit` uses ?

**Comment by TeamWolfyta** [comment]
Yup, `RateLimit` works on buttons.

**Comment by B0tis** [comment]
could you send me a Screenshot how you did that, i just get an error lol

**Comment by TeamWolfyta** [comment]
I already deleted the temp project I did it in but all's I did was:

```ts
@ButtonComponent({ id: "hello-btn" })
@Guard(
	RateLimit(TIME_UNIT.seconds, 30, {
		message: "Please wait `30` seconds!",
	})
)
helloBtn(interaction: ButtonInteraction): void {
	interaction.reply(`👋 ${interaction.member}`);
}
```

**Comment by B0tis** [comment]
ahhh lol, thx forgot the @Guards xD
