### ISSUE TITLE
[Bug]: Bot is not responding to commands, nor seeing any new messages in an event

### ISSUE THREAD

**Issue by ay0ks** [discordx-ts/discordx#891]
### What happened?

Bot is not responding to any of the commands, nor seeing any new messages in the `messageCreate` event.
![Screenshot_2022-11-01-04-58-48-755_com aliucord](https://user-images.githubusercontent.com/43708417/199155945-5db3372b-ea2c-4ed1-a799-1e26d65b21c2.png)
![Screenshot_2022-11-01-04-59-01-886_com termux](https://user-images.githubusercontent.com/43708417/199155956-43a95f47-beb2-4584-8771-3b3429fb5fc3.png)

Intents: 
```js
intents: [
    IntentsBitField.Flags.Guilds,
    IntentsBitField.Flags.GuildMembers,
    IntentsBitField.Flags.GuildMessages,
    IntentsBitField.Flags.GuildMessageReactions,
    IntentsBitField.Flags.GuildVoiceStates,
],
```

### Reproduction

1. Create project using `npx create-discordx`
2. Start the bot
3. Try to use any of the simple commands

### Package

discordx

### Version

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oceanroleplay** [comment]
try `IntentsBitField.Flags.MessageContent` intent

**Comment by oceanroleplay** [comment]
Let me know if it work out and use our discord server for more support.

https://discordx.js.org/discord
