### ISSUE TITLE
[Bug]: VS Code "node" launch configuration breaks slash command registration

### ISSUE THREAD

**Issue by megascatterbomb** [discordx-ts/discordx#945]
### What happened?

Launching this program via VS Code's "node" launch configuration causes commands to not register/become unregistered, however using the command line to launch node OR ts-node works fine.

### Expected behavior:
- All command line methods launch the discord bot, allowing the user to use the slash commands.
- VS Code launch configuration functions as expected, allowing the user to use the slash commands.

### Actual behavior:
- ✅ All command line methods launch the discord bot, allowing the user to use the slash commands.
- ❌ VS Code launch configuration does not register the commands properly, causing the bot to launch (appears online in discord) but not function at all.
  - Commands that were previously registered are unregistered when launching via the VS Code method. An example of this scenario is included in log output.

### Workaround
Changing the launch.json to simply execute ts-node is a workaround for this issue.

### Reproduction

Reproduction repo: https://github.com/megascatterbomb/MegaAntiCheat/tree/discordx-issue

Using: 
- node v18.16.0
- discordx 11.7.6
- @discordx/importer 1.2.2
- VS Code 1.70.2

Relevant code is in ./local

Create a .env in ./local, set the following
- DISCORD_TOKEN = "<bot token>"
- HEADLESS = "true"
- BOT_OWNER = "<your discord user id>"
- DEV_GUILD = "<id of guild you are testing in>"

From the root directory, execute in terminal `npm run build-local`
Once built, the following commands can be used to start the program (again, from the root directory)

- node ./local/build/index.js
- node ./local
- ts-node ./local/src/index.ts
- ts-node ./local

The problematic VS Code launch configuration called "Run Local Client" is provided in the repo (.vscode/launch.json).

### Package

discordx

### Version

Stable

### Relevant log output

```Shell
C:\Program Files\nodejs\node.exe .\local\build\index.js
--- MegaAntiCheat Local Client ---
Starting in headless mode...
client >> Events
	No event detected

client >> buttons
	No buttons detected

client >> select menu's
	No select menu detected

client >> modals
	No modal detected

client >> reactions
	No reaction detected

client >> context menu's
	No context menu detected

client >> application commands
	No application command detected

client >> simple commands
	No simple command detected

bot >> connecting discord...
Connected to Discord.
MegaCheaterDatabaseBeta >> commands >> global
	>> adding   0 [] 
	>> updating 0 [] 
	>> deleting 14 [stats, mark, group, lookup, friends, setcustomname, regengraph, import, importgroup, verbose, refresh, backup, restart, shutdown] 
	>> skipping 0 []
Bot started
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TeamWolfyta** [comment]
Scratch that, It wouldn't work with ts-node if you didn't invite the bot without that scope. 🤔

**Comment by samarmeena** [comment]
I have tested default launch config created by vscode. It's working fine. I recommend you to put breakpoints on importx and debug, what exactly processed there.

Reference for launch config: https://github.com/discordx-ts/discordx-bot/blob/main/.vscode/launch.json

**Comment by megascatterbomb** [comment]
Apologies for leaving this hanging, changing launch config to run ts-node in terminal is a sufficient fix.

**Comment by samarmeena** [comment]
> Apologies for leaving this hanging, changing launch config to run ts-node in terminal is a sufficient fix.

you can instead run npm script.
