### ISSUE TITLE
[Bug]: Invalid Return Type

### ISSUE THREAD

**Issue by britneygx** [discordx-ts/discordx#954]
### What happened?

In the [discordx/importer](https://github.com/discordx-ts/discordx/blob/main/packages/importer/index.d.ts) package, the Typescript definition for the `resolve` function should return `Promise<string[]>` rather than its current value of `string[]`.

### Reproduction

```typescript
import { resolve } from "@discordx/importer";
const pluginPaths = await resolve(`plugins/*`);
```

Typescript returns the following warning: `'await' has no effect on the type of this expression.ts(80007)`

### Package

@discordx/importer

### Version

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samarmeena** [comment]
Thank you for reporting this issue!!!
