### ISSUE TITLE
[Bug]: create-discordx 'module rimraf doesn ot provide an export named default'

### ISSUE THREAD

**Issue by mathewcst** [discordx-ts/discordx#962]
### What happened?

Hi, I just found this package and when I try to run the CLI I get this error:
![image](https://github.com/discordx-ts/discordx/assets/5620645/b1fef6c5-1667-49bd-8fba-8fc98a906f19)

Window 11
Node v20.9.0

### Reproduction

Just run `npx create-discordx`

### Package

discordx

### Version

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mathewcst** [comment]
rimraf v5 changed default export to named export 

```
v4 to v5
There is no default export anymore. Import the functions directly using, e.g., import { rimrafSync } from 'rimraf.
```

https://www.npmjs.com/package/rimraf

**Comment by samarmeena** [comment]
thanks @mathewcst
