### ISSUE TITLE
[Feature]: Update Lavalink to support V4

### ISSUE THREAD

**Issue by ElMehdiBouamama** [discordx-ts/discordx#999]
### Feature?

Lavalink has recently updated their library to V4 while introducing breaking changes that made the music features in this repo outdated. With time i suspect that the previous Lavalink V3.7 is not gonna be maintained and will probably cause breaking changes in this code base. I suggest to migrate the code base to a V4.0 preemptively before a shortage happens (which most surely is gonna happen in the future)
Here is a link to the new V4 Lavalink Release: https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.4

### Package

@discordx/lava-player

**Comment by ElMehdiBouamama** [comment]
Any news on this issue or should we swap out of the library?

**Comment by ElMehdiBouamama** [comment]
I will try to make a pull request with the adequate changes. I was about to migrate to a new library, but if this is still active, i can contribute.

**Comment by samarmeena** [comment]
@ElMehdiBouamama just wanted to ask, are you familiar with changes or if you have tried them?

**Comment by ElMehdiBouamama** [comment]
I haven't tried the changes yet, but i will experiment with it and get familiar.

**Comment by samarmeena** [comment]
I am doing some testings, you can connect with me in our discordx server.

**Comment by samarmeena** [comment]
@ElMehdiBouamama Lavalink v4 support has been released. If you are using our plugin, it will be updated shortly. Thank you for reminding me about this upgrade; it was indeed necessary.
